mode = "dark"
accent = "#B9C1AA"
selection = "#3B5344"
selection_foreground = "#EEE7D5"
selection_background = "#3B5344"
muted = "#91A38C"
background = "#142923"
dark_background = "#10211D"
darker_background = "#0C1916"
lighter_background = "#21392F"
foreground = "#DED7C4"
dark_foreground = "#91A38C"
light_foreground = "#CBC8B5"
bright_foreground = "#EEE7D5"
hyprland_active_border = "#B9C1AA"
hyprland_inactive_border = "#405448"
red = "#DED7C4"
green = "#B9C1AA"
yellow = "#CBC8B5"
orange = "#CBC8B5"
blue = "#B9C1AA"
magenta = "#DED7C4"
cyan = "#91A38C"
brown = "#91A38C"
bright_red = "#EEE7D5"
bright_green = "#DED7C4"
bright_yellow = "#EEE7D5"
bright_blue = "#CBC8B5"
bright_magenta = "#DED7C4"
bright_cyan = "#B9C1AA"
